Repository zenn-dev/zenn-vscode-extension, pull requests merged in 2023-01, with the labels that each got.

#39 release v0.0.6
  README.md
  package.json
  snippets/snippets.json
  src/schemas/article.ts
  src/schemas/book.ts
  src/schemas/bookChapter.ts
  src/webviews/src/components/BookPreview/BookPreview.module.scss
  src/webviews/src/components/BookPreview/index.tsx
Labels: release:patch

#44 fix: validate-pr 内で Bot によるコメントをしないように修正
  .github/workflows/validate-pr.yml
Labels: fix

#43 fix: ポリシーコメントを廃止して PULL_REQUEST_TEMPLATE を導入した
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/policy-comment.yml
Labels: feature

#42 fix: `fatal: refusing to merge unrelated histories` エラーが出てしまう問題を修正
  .github/workflows/release.yml
Labels: bugfix

#45 release v0.0.7
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/policy-comment.yml
  .github/workflows/release.yml
  .github/workflows/validate-pr.yml
  package.json
Labels: release:patch

#47 fix: release-workflow で canary に最新コミットを push できない問題を修正
  .github/workflows/release.yml
Labels: bugfix

#48 release v0.0.8
  .github/workflows/release.yml
  package.json
Labels: release:patch

#50 fix: Book の プレビュー画面にてサマリー項目が zenn-cli と異なる問題を修正
  package.json
  src/utils/helpers.ts
  src/webviews/src/components/BookPreview/BookPreview.module.scss
  yarn.lock
Labels: bugfix

#51 fix: js-yamlに変えたことによる型エラーを修正
  src/utils/helpers.ts
Labels: fix

#53 feat: チャプターの新規作成コマンドの追加
  package.json
  src/commands/newBook.ts
  src/commands/newChapter.ts
  src/context/commands.ts
  src/variables.ts
Labels: feature

#57 fix: コマンドパレットから実行しやすいようにコマンドのタイトルを修正
  package.json
  src/commands/preview.ts
Labels: fix

#56 release v0.0.9
  package.json
  src/commands/newBook.ts
  src/commands/newChapter.ts
  src/commands/preview.ts
  src/context/commands.ts
  src/utils/helpers.ts
  src/variables.ts
  src/webviews/src/components/BookPreview/BookPreview.module.scss
  yarn.lock
Labels: release:patch
