Repository zenn-dev/zenn-vscode-extension, pull requests merged in 2023-02, with the labels that each got.

#59 feat: ガイド記事一覧機能の追加
  README.md
  package.json
  src/commands/openGuide.ts
  src/context/commands.ts
  src/context/treeview.ts
  src/schemas/guide.ts
  src/treeview/guide/guideTreeItem.ts
  src/treeview/guide/guideTreeViewProvider.ts
  src/types.ts
  src/variables.ts
Labels: feature

#65 fix: フロントマターの published_at の項目が正しくプレビューされるように修正
  examples/articles/scheduled-post.md
  src/utils/helpers.ts
Labels: bugfix

#63 feat: 英語による検索性と日本語による分かりやすさの両立のためにコマンドをローカライズ化
  package.json
  package.nls.ja.json
  package.nls.json
Labels: feature

#61 feat: アクティブファイルのプレビュー機能の追加
  README.md
  examples/outside-of-right-folders.md
  package.json
  src/commands/preview.ts
  src/schemas/previewPanel.ts
Labels: feature

#71 fix: WebView内のリンクが正しく動作しないバグを修正
  src/context/app.ts
  src/context/webview.ts
  src/schemas/article.ts
  src/schemas/book.ts
  src/schemas/bookChapter.ts
  src/schemas/previewPanel.ts
  src/types.ts
  src/utils/vscodeHelpers.ts
  src/webviews/src/components/BookChapterPreview/index.tsx
  src/webviews/src/components/BookPreview/index.tsx
Labels: bugfix

#69 release v0.1.0
  README.md
  examples/articles/scheduled-post.md
  examples/outside-of-right-folders.md
  package.json
  package.nls.ja.json
  package.nls.json
  src/commands/openGuide.ts
  src/commands/preview.ts
  src/context/app.ts
  src/context/commands.ts
  src/context/treeview.ts
  src/context/webview.ts
  src/schemas/article.ts
  src/schemas/book.ts
  src/schemas/bookChapter.ts
  src/schemas/guide.ts
  src/schemas/previewPanel.ts
  src/treeview/guide/guideTreeItem.ts
  src/treeview/guide/guideTreeViewProvider.ts
  src/types.ts
  src/utils/helpers.ts
  src/utils/vscodeHelpers.ts
  src/variables.ts
  src/webviews/src/components/BookChapterPreview/index.tsx
  src/webviews/src/components/BookPreview/index.tsx
Labels: release:minor

#73 fix: 同一画像のリンクが複数個ある場合に１つ目しかレンダリングされないバグを修正
  examples/articles/local-image-test.md
  src/utils/markdownHelpers.ts
Labels: bugfix

#68 feat: チャプターファイルをチャプター番号で並べ替え表示する機能の追加
  README.md
  examples/.vscode/settings.json
  examples/books/chapter-number-sort/1-example.md
  examples/books/chapter-number-sort/999.excluded.md
  examples/books/chapter-number-sort/config.yaml
  examples/books/chapter-number-sort/example2.md
  examples/books/chapter-number-sort/example3.md
  examples/books/chapter-number-sort/excluded-file.md
  examples/books/oder-chapter-example-book/1000.excess.md
  package.json
  src/schemas/book.ts
  src/treeview/book/bookChapterTreeItem.ts
  src/treeview/book/bookTreeItem.ts
Labels: feature

#79 fix: articlesやbooksフォルダが無い場合のエラーメッセージが表示されないよう修正
  src/treeview/article/articlesTreeViewProvider.ts
  src/treeview/book/booksTreeViewProvider.ts
Labels: bugfix

#82 feat: zenn-content-css とその他関連ライブラリのアップデート
  package.json
  src/webviews/src/components/ArticlePreview/index.tsx
  src/webviews/src/components/BookChapterPreview/index.tsx
  src/webviews/src/components/BookPreview/index.tsx
  src/webviews/src/components/ValidationErrors/index.tsx
  webpack.config.js
  yarn.lock
Labels: feature

#83 release v0.1.1
  README.md
  examples/.vscode/settings.json
  examples/articles/local-image-test.md
  examples/books/chapter-number-sort/1-example.md
  examples/books/chapter-number-sort/999.excluded.md
  examples/books/chapter-number-sort/config.yaml
  examples/books/chapter-number-sort/example2.md
  examples/books/chapter-number-sort/example3.md
  examples/books/chapter-number-sort/excluded-file.md
  examples/books/oder-chapter-example-book/1000.excess.md
  package.json
  src/schemas/book.ts
  src/treeview/article/articlesTreeViewProvider.ts
  src/treeview/book/bookChapterTreeItem.ts
  src/treeview/book/bookTreeItem.ts
  src/treeview/book/booksTreeViewProvider.ts
  src/utils/markdownHelpers.ts
  src/webviews/src/components/ArticlePreview/index.tsx
  src/webviews/src/components/BookChapterPreview/index.tsx
  src/webviews/src/components/BookPreview/index.tsx
  src/webviews/src/components/ValidationErrors/index.tsx
  webpack.config.js
  yarn.lock
Labels: release:patch

#75 improve: アクティブファイルがプレビュー可能な時のみプレビューボタンが表示されるように改善
  package.json
  src/context/editor/index.ts
  src/schemas/previewPanel.ts
Labels: fix

#85 chore: package.json に homepage フィールドを追加
  package.json
Labels: chore

#86 chore: Pull Request テンプレートの見出しレベルを調整
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#77 feat: テンプレート作成後に編集作業をすぐに始められるように作成したファイルを開く機能を追加
  src/commands/newArticle.ts
  src/commands/newBook.ts
  src/commands/newChapter.ts
Labels: feature

#88 docs: VSCode の `editor.quickSuggestions` スキーマ変更を反映
  README.md
Labels: chore

#90 fix: プレビュー画面でリポジトリ管理の画像が正しく表示されない不具合修正
  examples/articles/local-image-test.md
  examples/images/example-images/zenn-icon.png
  src/utils/markdownHelpers.ts
Labels: bugfix

#91 release v0.1.2
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  examples/articles/local-image-test.md
  examples/images/example-images/zenn-icon.png
  package.json
  src/commands/newArticle.ts
  src/commands/newBook.ts
  src/commands/newChapter.ts
  src/context/editor/index.ts
  src/schemas/previewPanel.ts
  src/utils/markdownHelpers.ts
Labels: release:patch

#87 docs: チャプター作成機能の記述の追記及び説明の詳細化
  README.md
Labels: chore

#81 feat: 現在開いているファイルのツリービューアイテムをハイライトする機能を追加
  package.json
  package.nls.ja.json
  package.nls.json
  src/commands/revealActiveFile.ts
  src/context/commands.ts
  src/context/treeview.ts
  src/treeview/article/articleTreeItem.ts
  src/treeview/article/articlesTreeViewProvider.ts
  src/treeview/book/bookConfigTreeItem.ts
  src/treeview/book/bookTreeItem.ts
  src/treeview/book/booksTreeViewProvider.ts
  src/types.ts
  src/utils/vscodeHelpers.ts
  src/variables.ts
Labels: feature

#93 fix: 埋め込み要素のレンダリングバグを修正
  src/utils/markdownHelpers.ts
Labels: bugfix

#92 release v0.1.3
  README.md
  package.json
  package.nls.ja.json
  package.nls.json
  src/commands/revealActiveFile.ts
  src/context/commands.ts
  src/context/treeview.ts
  src/treeview/article/articleTreeItem.ts
  src/treeview/article/articlesTreeViewProvider.ts
  src/treeview/book/bookConfigTreeItem.ts
  src/treeview/book/bookTreeItem.ts
  src/treeview/book/booksTreeViewProvider.ts
  src/types.ts
  src/utils/markdownHelpers.ts
  src/utils/vscodeHelpers.ts
  src/variables.ts
Labels: release:patch
