Repository zenn-dev/zenn-vscode-extension, pull requests merged in 2023-03, with the labels that each got.

#95 feat: yarn をやめて pnpm に移行する
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/update-release-version.yml
  .vscode/launch.json
  .vscode/tasks.json
  .vscodeignore
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: feature

#97 fix: pnpm version コマンドのオプションが間違っていたので修正
  .github/workflows/update-release-version.yml
Labels: bugfix

#98 refactor: 無駄なasyncキーワードの削除
  src/commands/revealActiveFile.ts
Labels: fix

#101 feat: プレビューパネルのタブタイトルの切り詰め表示機能の追加
  examples/.vscode/settings.json
  examples/articles/too-long-title.md
  package.json
  src/schemas/previewPanel.ts
Labels: feature

#96 release v0.1.4
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/update-release-version.yml
  .vscode/launch.json
  .vscode/tasks.json
  .vscodeignore
  CONTRIBUTING.md
  README.md
  examples/.vscode/settings.json
  examples/articles/too-long-title.md
  package.json
  pnpm-lock.yaml
  src/commands/revealActiveFile.ts
  src/schemas/previewPanel.ts
  yarn.lock
Labels: release:patch

#104 fix: publish が上手くいかない問題を修正
  .github/workflows/release.yml
  .vscodeignore
  .yarnrc
Labels: bugfix

#106 fix: npm でも実行できるようにコマンドを修正
  package.json
Labels: bugfix

#107 fix: `vscode:prepublish` を npm-run-all を使わずに実行するようにした
  package.json
Labels: bugfix
